// Code generated by "stringer -type SnmpVersion"; DO NOT EDIT.

package gosnmp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Version1-0]
	_ = x[Version2c-1]
	_ = x[Version3-3]
}

const (
	_SnmpVersion_name_0 = "Version1Version2c"
	_SnmpVersion_name_1 = "Version3"
)

var (
	_SnmpVersion_index_0 = [...]uint8{0, 8, 17}
)

func (i SnmpVersion) String() string {
	switch {
	case i <= 1:
		return _SnmpVersion_name_0[_SnmpVersion_index_0[i]:_SnmpVersion_index_0[i+1]]
	case i == 3:
		return _SnmpVersion_name_1
	default:
		return "SnmpVersion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
